### ISSUE TITLE
Broken link for Happy Bear Software article

### ISSUE THREAD

**Issue by a6macleod** [TheOdinProject/theodinproject#1026]
In https://www.theodinproject.com/lessons/strategy the link to https://www.happybearsoftware.com/how-to-get-a-programmer-job.html goes to the heroku "no such app" page. It looks like perhaps Happy Bear Software has closed. This will probably need a new article to replace it.

**Comment by tfantina** [comment]
I'm trying to contact the Happy Bear people to see if we can repost this article elsewhere.

**Comment by leila-alderman** [comment]
@a6macleod @tfantina Thanks for posting and working on this issue! There is already an issue open for this article open in our curriculum repo (https://github.com/TheOdinProject/curriculum/issues/12374), so I'm going to close this issue so that we aren't duplicating work. Feel free to jump in over there!
