### ISSUE TITLE
MD Previewer does not persist styling for multi-line code blocks

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/theodinproject#1652]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/22967723/104485525-7362e280-557f-11eb-999e-b600a6406413.gif)

- currently these code blocks do not persist their styling on [the markdown previewer](https://theodinproject.com/lessons/preview) if one swaps between the content and preview tab multiple times

**Comment by marvingay** [comment]
@KevinMulhern Is Prism's `highlightAll()` expensive, performance wise?

This occurs because the convertedContent doesn't change on tab switches. We can either paint on each request to Preview if performance is a non-issue or add a piece of state and handlers to manage whether or not we should paint independent of the content.

**Comment by KevinMulhern** [comment]
Hey @marvingay, nice work tracking down the issue. 

 I _think_ its ok performance wise. It's pretty light weight. Firing it off on the preview tab switch sounds like a good approach to me 👍
