### ISSUE TITLE
Chore: Fix ActionText::ContentHelper and ActionText::TagHelper Depreciation Warning on Boot

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1844]
### Description
We get the following depreciation warning when booting the app:
![Screenshot 2021-04-15 at 20 31 03](https://user-images.githubusercontent.com/7963776/114927758-c15edf00-9e29-11eb-8745-b303c33342e5.png)

### Acceptance Criteria
We shouldn't get any depreciation warnings when booting the app.

### Additional Information
We aren't using ActionText::ContentHelper or ActionText::TagHelper anywhere in our app code as far as I can tell. This is probably caused by a gem.

**Comment by rankoliang** [comment]
After some digging, I found that the issue occurs when requiring `"rails/all"` in application.rb:
https://github.com/TheOdinProject/theodinproject/blob/b83eb11811196a849032001f2412657d41db3b85/config/application.rb#L3

`"rails/all"` imports all of the individual rails frameworks as shown in this link:
https://guides.rubyonrails.org/initialization.html#railties-lib-rails-all-rb

The deprecation warning occurs when requiring 'action_text/engine'.

There was a fix I found that replaced the require statement with the following code in application.rb that works to fix the deprecation warning (source: https://github.com/rails/rails/issues/36546#issuecomment-763329919).
```ruby
require "rails"

%w(
  active_record/railtie
  active_storage/engine
  action_controller/railtie
  action_view/railtie
  action_mailer/railtie
  active_job/railtie
  action_cable/engine
  action_mailbox/engine
  rails/test_unit/railtie
  sprockets/railtie
).each do |railtie|
  begin
    require railtie
  rescue LoadError
  end
end
```
The only change here from the code in `"rails/all"` is that `"action_text/engine"` is removed from the array.

However, this file may need to be updated whenever "rails/all" is updated in the future if there are any major changes to it or of new frameworks are added. How do you feel about this fix?

**Comment by rankoliang** [comment]
I've narrowed down the problem even further and I've found out that the real issue is that when `ActionMailer` is loaded, `ActionText` also loads it helpers (https://github.com/rails/rails/blob/c431432f93a35530cd0544192b93dabda51f2bf7/actiontext/lib/action_text/engine.rb#L47-L51). If this is loaded too early, it will cause the deprecation warning.

This happens in the file
https://github.com/TheOdinProject/theodinproject/blob/master/config/initializers/smtp.rb
where we set the smtp settings.

A workaround could be to run the setup after Rails is initialized as suggested in https://github.com/rails/rails/issues/41721.
```ruby
Rails.application.config.after_initialize do
  ActionMailer::Base.smtp_settings = {
    address: 'smtp.sendgrid.net',
    port: '587',
    authentication: :plain,
    user_name: ENV['SENDGRID_USERNAME'],
    password: ENV['SENDGRID_PASSWORD'],
    domain: 'heroku.com',
    enable_starttls_auto: true
  }
end
```

A fix for the root cause has been shipped to the rails repo and I have verified it fixes the deprecation warning by manually updating `engine.rb`. However, it does not seem like the fix is shipped in the latest version of rails / ActionText on rubygems.

When the fix is finally shipped, it should be as simple as bumping the rails version up. If the workaround above is still implemented, it is suggested that it be removed when rails is updated with the fix.

**Comment by KevinMulhern** [comment]
Thanks for digging into this @rankoliang, brilliant work getting to the bottom of it 💪 

I think the second solution is the way to go. Theres nothing wrong with the first either other than it needs more code changes. We can make a note of removing it when the Rails bump is shipped in the future.
