### ISSUE TITLE
Chore: Upgrade the App to Ruby 2.7.1

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1845]
### Description
The change to kwargs means we should upgrade to this version of Ruby 2.7 first to be safe. 

### Acceptance Criteria
The app is running on Ruby 2.7.1 without any deprecation warnings.

**Comment by Blakelist7** [comment]
Hey, 
@KevinMulhern Mind guiding me how to Upgrade? Always had in mind how, we upgrade the App from one version to another. Thought this will be the perfect task for it.

**Comment by KevinMulhern** [comment]
Hey @Blakelist7, it should be a pretty straight forward upgrade since we don't have a ton of service objects and we keep our gems fairly up to date with Dependabot.

1. First thing to do is make sure ruby 2.7.1 is installed locally.
2. Then switch the version in the .ruby-version file in the root directory of the app.
3. Run bundle install
4. Run the test suite and fix any failing tests and depreciation warnings.
5. To make sure CI works with the updated version we will have to update our ruby image in the [circle ci config file](https://github.com/TheOdinProject/theodinproject/blob/main/.circleci/config.yml#L7). I think switching it to `image: circleci/ruby:2.7.1-node` should work

That should be it, but I could be missing a few things. In any case we can revaluate when the above is done 😄

**Comment by Blakelist7** [comment]
@KevinMulhern Could you help me with this
`An error occurred while loading rails_helper.
Failure/Error: ActiveRecord::Migration[6.0].maintain_test_schema!

ActiveRecord::ConnectionNotEstablished:
  could not connect to server: Connection refused
  	Is the server running on host "localhost" (127.0.0.1) and accepting
  	TCP/IP connections on port 5432?
# ./spec/rails_helper.rb:12:in `<top (required)>'
# ------------------
# --- Caused by: ---
# PG::ConnectionBad:
#   could not connect to server: Connection refused
#   	Is the server running on host "localhost" (127.0.0.1) and accepting
#   	TCP/IP connections on port 5432?
#   ./spec/rails_helper.rb:12:in `<top (required)>'
No examples found.


Finished in 0.00007 seconds (files took 3.53 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Coverage report generated for RSpec to /home/blakelist7/Documents/theodinproject/coverage. 115 / 1590 LOC (7.23%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
`
`rspec` triggers this error.

**Comment by Blakelist7** [comment]
@KevinMulhern To run the test suite I have to execute `rspec` command?

**Comment by Blakelist7** [comment]
@KevinMulhern Thanks for guiding me. 
I have completed the above steps but could you tell me why CI tests are failing?

**Comment by KevinMulhern** [comment]
Hey @Blakelist7, it looks like Circle doesn't recognise the docker image you're requesting. Circle have a list of all available images here: https://circleci.com/docs/2.0/docker-image-tags.json

I think this `ruby:2.7.1-stretch-node-browsers-legacy` needs to change to `ruby:2.7.1-node` in the Circle config file to get it working.
