### ISSUE TITLE
Feature: Broken link notification message copy

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#2019]
#### Description
The proposed wording for the broken link notification message

### Action Required

Your project submission in [lesson](link_to_lesson) was flagged because it has a broken link. We need you to fix it within 7 days from \<insert date\> otherwise the project will be removed from the project submissions list.

Your assistance is appreciated.

The Odin Project Team

**Comment by KevinMulhern** [comment]
Looks really good @CouchofTomato, what do you think about adding a little more personable language with an explanation as to why we remove them?

I think it might be received a bit better and answer any questions about why it will be removed.


> Action Required
Hey **username**, heads up your project submission for **lesson name** was flagged because it has a broken link. We aim to keep the submission lists useful and so we remove any submissions with broken links often. When you get a moment, can you  update your submission with the correct links for us please? Otherwise we will have to remove it on the **date**. 

> Thanks for your help,

> The Odin Project Team
