### ISSUE TITLE
Repairing front-end

### ISSUE THREAD

**Issue by iansowinski** [TheOdinProject/theodinproject#241]
***Things that are working badly:***
- [ ] white margin on the right side in desktop view
- [ ] right and left margins in mobile view
- [ ] sign-in forms and github button at login site is not responsive
- [ ] mobile hamburger menu button could look nicer (only shadow makes lines visible)
- [ ] "having a path", "building a portfolio" and "learning together" divs are not in the middle in mobile view
- [ ] "what you'll learn" and "why this project rocks" need some nicer illustrations
- [ ] Someone should definitely work on pictures and colors - it's a mess on the landing page

**Comment by KevinMulhern** [comment]
Hey @iansowinski, thanks for opening this 😄 
We have been putting off major front end changes because we are in the process of re designing the site at the moment. The front end of the site will probably have to be completely rewritten to implement our new design so most of these problems will be fixed in that project.

**Comment by iansowinski** [comment]
So I assume, issue can be closed 😄

**Comment by KevinMulhern** [comment]
Yeah it can be closed, thank you again for putting it together though and please feel free to create more issues if you find anything 😄
