### ISSUE TITLE
Feature: Installations (appendix) page on the website

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/theodinproject#2506]
## Description

A static webpage that has a list of all the lessons where The Odin Project invites the user to install a technology. A link to the webpage will be available on the footer of the website called "appendix".

## Suggested Implementation (outdated: look at this issue's comments for proposed implementation)

 - Put all the lesson links in a markdown file. At the bare minimum, it has links to the virtualbox, git, dual-boot, chrome, nodejs, ruby, and rails installation lessons. It must cover every installation throughout the entire curriculum.
                   - Should one-off setup directions be included here? For example, webpack and react. (TBD)
                   - TOP references external resources for setting up some technologies. For example, eslint. Should those be added here? (TBD)
- Use the markdown converter and create a html.erb file.
                   -  Setup its route so it's live at [https://www.theodinproject.com/appendix](https://www.theodinproject.com/appendix)
                   -  It will have the same styling as the [community_rules](https://www.theodinproject.com/community_rules) page 
- A link called "appendix" which takes to the said page. It must live on the footer of the website. Exact location TBD

## Acceptance Criteria:
- [x] Add an `installation_lesson` column to the lessons table in the db
- [x] Set the `installation_lesson` property of the installation lessons as true
- [x] Add an html file that loops over installation lessons and displays their title
- [x] Style installation lessons appendix page
- [x] Add an "appendix" link to the footer of the website

## Additional Information:

n/a

**Comment by KevinMulhern** [comment]
I love this idea @01zulfi ❤️ 

Just a couple of suggestions on the implementation. 

* I think we can use an HTML page instead of markdown for this. Unless there's a really good reason to use markdown instead? 
* We could add a new `installation_lesson` column to the lessons table which would hold a boolean value set to false by default. Then in the seeds, we would set any of the specific installation lessons we want as true. That would allow us to have a very simple view since we would only need to loop through and display any lessons which have `installation_lesson` set to true. It also makes it easier to add new installation lessons to the appendix in the future since we wouldn't have to touch the view and would only need to make a one-line change on the seeds.

**Comment by KevinMulhern** [comment]
Another benefit and the biggest reason we should be using the database to handle this instead is if any of the installation lessons get removed or have their name changed etc the links on the appendix would change automatically to reflect whatever changes happen. Whereas if the links are hardcoded we would have to remember to manually update them on the appendix instead.

**Comment by 01zulfi** [comment]
@KevinMulhern Thanks for the feedback. I agree with your implementation and it would certainly make the appendix easily maintainable. Unfortunately, I'm not versed in databases as of yet, and I'm afraid I lack the knowledge of where and how to make the changes you propose.

**Comment by 01zulfi** [comment]
Closing this now since all tasks have been completed :rocket:
