### ISSUE TITLE
HTTP status code pages: update to match modern styling

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3660]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Update 
- https://github.com/TheOdinProject/theodinproject/blob/main/public/500.html
- https://github.com/TheOdinProject/theodinproject/blob/main/public/400.html 
- https://github.com/TheOdinProject/theodinproject/blob/main/public/422.html 
to the modern visual styling of TOP, as these in general haven't been touched since *2013* when they were initially committed to a very embryonic odin project

**2. Acceptance Criteria:**
- [ ] all these pages are updated to TOP's current visual style

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Asartea, totally agree. Our exceptions pages haven't been looked at in quite some time. 

For whoever picks this up, it would be worth researching handling custom exception pages in Rails. We're using a [custom exceptions app](https://github.com/TheOdinProject/theodinproject/blob/main/lib/custom_public_exceptions.rb), but that was done quite a few years ago and I'm not sure if that's still the correct/modern way of doing it with Rails.

**Comment by CouchofTomato** [comment]
The relevant section of the rails guides is https://guides.rubyonrails.org/v7.0.4.2/action_controller_overview.html#the-default-500-and-404-templates

**Comment by Asartea** [comment]
I would be willing to tackle the styles part (just copying TOP's modern light mode text and link styles, and possibly somewhat copying wording from the 404 page), but don't have the knowledge to look into the custom exceptions part

**Comment by KevinMulhern** [comment]
Hey @Asartea, thanks for being willing to take this on. I just have a few of notes before you start:

* We can remove the 400 file altogether. It's been dropped from new Rails apps and we only raise 404 or 422 errors in that range anyway.
* If a 500 error is raised because of a problem on Heroku etc, it might not be making it to our app code so using Tailwind for this page would be risky. Something static and [very simple like this](https://tailwindui.com/components/marketing/feedback/404-pages#component-ebef3404d06e7b5f42e85b7b2ca4a2a5)  would be best. 
* The 422 page can use the same styling as the 404 page, but will need to be setup the same way within the app with the custom exceptions to do so. It might be best to leave this as is and raise another issue for it.

**Comment by Asartea** [comment]
> If a 500 error is raised because of a problem on Heroku etc, it might not be making it to our app code so using Tailwind for this page would be risky. Something static and very simple like this would be best.

I tested this already, and nothing in /public gets any outside styling in any way, so Tailwind won't work fullstop.

**Comment by Asartea** [comment]
Yes; I think the best way to do it would be to close this with a PR that changes the styling on `422.html` and `500.html` and drops `400.html`, and then file follow up issues for A) exploring/deciding what the best way to handle these pages is, and then B) moving the pages to that system

**Comment by KevinMulhern** [comment]
Yep, splitting it up sounds great to me.

To make things a little easier, 500 is probably the only page that really needs work. Users will never see the 422 page, we only respond with a 422 status on invalid form submissions and we always redirect on to somewhere else.
