### ISSUE TITLE
Feature: Username field is autofocused when visiting sign up page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3875]
**1. Description of the Feature Request:**
_When I'm signing up, then I want the username field to be focused automatically, so I can start entering my credentials straight away_

**2. Acceptance Criteria:**
1. Click the "Get started" button on the navbar
2. The username field should be auto focused. 

**3. Additional Information:**
* We have a autofocus value already set - `autofocus: params[:email].present?`
* But we no longer use this, so it can be replaced with `autofocus: true` to satisfy the acceptance criteria.

**Comment by j-mcQueen** [comment]
Hey, I'd love to work on this too! As I'm sure you're aware, I've requested to work on #3874 too, so if you'd rather assign that to someone else then no worries :-)

**Comment by KevinMulhern** [comment]
Hey @j-mcQueen , I've assigned the other one to you and we'll leave this one for someone else's first contribution. Thanks for being willing to take both on though 💪 much appreciated.

**Comment by rudnam** [comment]
Hi! Can I work on this?

**Comment by CouchofTomato** [comment]
@rudnam All yours

**Comment by rudnam** [comment]
There seems to be a problem with the tests trying to click the google/github buttons in the sign up form. Since the username field is focused initially, the attempt to click the button only removes focus from the username field now. It needs to click one more time before the button is clicked.

Screenshot:
![image](https://github.com/TheOdinProject/theodinproject/assets/70255485/abf7b4d0-5ca7-4340-8074-d5adaa7ba056)

**Comment by CouchofTomato** [comment]
Hey @rudnam , if you create a PR for your work so far we can pull it down and take a look.

**Comment by rudnam** [comment]
I created a PR for it now here https://github.com/TheOdinProject/theodinproject/pull/3891

**Comment by Asartea** [comment]
> I created a PR for it now here https://github.com/TheOdinProject/theodinproject/pull/3891

These test errors are from [github.com/TheOdinProject/theodinproject/blob/main/spec/system/sign_up_spec.rb#L47](https://github.com/TheOdinProject/theodinproject/blob/7ca1eac3efe209868a71f6fa7fcd60c43a3a3e14/spec/system/sign_up_spec.rb#L47) and further down; rspec expects a single click on the button to be enough to press it, but due to the autofocus it now needs two clicks.

Appending a extra `.click` for each click for the oauth specs should be enough to make them pass again
