### ISSUE TITLE
Add a Comparison graph

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/theodinproject#3916]
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

When I go to the About section of the website, I would like to see what makes TOP different from other  coding curriculums when I can easily get my education at FreecodeCamp (Note: I’m speaking from the perspective from a coding newbie who decided to check TOP but is considering FCC).
**2. Acceptance Criteria:**

I’m open to collaborating with others

**Comment by CouchofTomato** [comment]
Hey @CBID2 

Thanks for the idea. I'm not entirely against it although would want to be careful about how it's framed. While we might take a different approach to FCC and similar sites in how we want people to learn web dev, we do think they're doing amazing things.

Overall I do think it could help clarify what learners can expect. I'll russle up some other opinions.

**Comment by CBID2** [comment]
> Hey @CBID2 
> 
> 
> 
> Thanks for the idea. I'm not entirely against it although would want to be careful about how it's framed. While we might take a different approach to FCC and similar sites in how we want people to learn web dev, we do think they're doing amazing things.
> 
> 
> 
> Overall I do think it could help clarify what learners can expect. I'll russle up some other opinions.

Great I can't wait

**Comment by rlmoser99** [comment]
I am not a big fan of a graph that shows how we are different than FCC or other paths to learn web development because it makes me feel like we are selling something. Plus I think it would be really hard to compare apples and oranges.

I am not opposed to listing what learners can expect to learn at TOP, because I think this gets to the heart of the matter without bashing FCC or other resources (which I think is a bad look on our part).

**Comment by CBID2** [comment]
> I am not a big fan of a graph that shows how we are different than FCC or other paths to learn web development because it makes me feel like we are selling something. Plus I think it would be really hard to compare apples and oranges.
> 
> I am not opposed to listing what learners can expect to learn at TOP, because I think this gets to the heart of the matter without bashing FCC or other resources (which I think is a bad look on our part).

Oh no just to be clear @rlmoser99, this chart won't bash FreeCodecamp. It's just to point out what makes TOP distinctive from FCC. Something like [this(I'm mostly talking structure-wise)](https://www.compsmag.com/vs/codecademy-vs-freecodecamp/).

**Comment by CouchofTomato** [comment]
What I'm not sure about is how much value it will add. Clearly we're going to be biased so would it actually provide something useful. We have an FAQ already to address key points about TOP. Would this add anything?

**Comment by ManonLef** [comment]
I personally don't see the added value for a comparison. It would feel like a competitive move between two different courses. In this example specifically FCC. When people pick a course that they will dedicate months or even years to, I hope they exercise due diligence.

**Comment by rlmoser99** [comment]
Maybe the wording "bash FreeCodecamp" is too harsh, but I think comparing us to any other platform is like comparing apples to oranges.

Like our requirement to set up your own dev environment on your computer is a key difference so our course can't be completed on a mobile app - this is intentional and we believe is a better approach. We don't offer a certificate, but if you complete either full-stack course, you'll have a portfolio of projects that demonstrates your ability.

Both of these examples are covered in our FAQ, so I do not think we need a comparison graph on the about me page.

**Comment by CBID2** [comment]
> Maybe the wording "bash FreeCodecamp" is too harsh, but I think comparing us to any other platform is like comparing apples to oranges.
> 
> 
> 
> Like our requirement to set up your own dev environment on your computer is a key difference so our course can't be completed on a mobile app - this is intentional and we believe is a better approach. We don't offer a certificate, but if you complete either full-stack course, you'll have a portfolio of projects that demonstrates your ability.
> 
> 
> 
> Both of these examples are covered in our FAQ, so I do not think we need a comparison graph on the about me page.

Ohh ok

**Comment by CouchofTomato** [comment]
I'm closing this out because there isn't the necessary support for it.
