### ISSUE TITLE
Fix remaining uses of text-gold-600

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3962]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
We currently use(d) `text-gold-600` as the primary accent color for text we wanted to draw extra attention to and links. This color has inherent accessibility problems however, due to bad contrast with both the background colors TOP uses. We should change all remaining occurrences of this within TOP to an accessible alternative.

For in-text links such as the FAQ components I think it would make most sense to transition them to the same design we currently use for in lesson links; links which aren't neatly in the prose could instead be changed to the same design we currently use for say the view all success stories link on the main page:

![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/874f9185-ffd7-4bef-a3f5-bde694422542)

**2. Acceptance Criteria:**
- [ ] Decide what we want to do with the remaining uses
- [ ] Change all uses over

**3. Additional Information:**
See https://github.com/search?q=repo%3ATheOdinProject%2Ftheodinproject%20%22text-gold-600%22&type=code for a full list of affected files

**Comment by KevinMulhern** [comment]
Changing UI links to the same as the more success stories link sounds great to me. 

For anything in remaining in prose such as the faq. I don't think the blue and purple will have as much utility. It's good for larger pieces of content, but the faq is a marketing page and won't need visited state. Following what the Open source section of the about page is doing with links should fit in nice:

<img width="409" alt="Screenshot 2023-07-13 at 18 39 38" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/2430fa1f-6088-47f8-8ad8-b7393c72f9d1">


Theres only really one non negotiable occurrence of gold-600 text we need to keep lol - the main heading on the home page. It needs to stay for branding. But I think thats fine in light house any way because of how large it is?

**Comment by Asartea** [comment]
Yeah, the main heading text is large, so it counts under the large standards, under which it meets AAA
