### ISSUE TITLE
Redesign: FAQ Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#400]
This task is to implement a redesigned faq page as shown in the mock up images below. This is our current faq page and where you can find the content for the faq http://www.theodinproject.com/faq

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing) 

### FAQ Redesign
![faq](https://cloud.githubusercontent.com/assets/7963776/24628734/7851fc24-18af-11e7-8b16-8787c6cff6c6.png)

### FAQ Expanded
![faq-expanded](https://cloud.githubusercontent.com/assets/7963776/24629241/3de074c0-18b0-11e7-8490-727ad2ed51ba.png)

**Comment by KevinMulhern** [comment]
@arun1595 is working on this 😄

**Comment by adachiu** [comment]
@arun1595 I have some feedback based on https://staging-odin-project.herokuapp.com/faq?ref=homenav

1. We don't need the media query for (min-width: 1200px) because the 1140px length looks way too long; too much space between the question and the `+` sign.
2. The H5 for questions should be font-size 24px and `color: rgba(74, 74, 74, 0.7);`
3. The `+` icon could be increased to double its size because it's a bit too small right now
4. The `#faq-accordion` could have padding of 6em
5. Increase the padding between the "Open Gitter" button and the footer. It could be the same spacing as the `#faq-accordion` and "Got questions" text.
6. The "Got questions" text is `rgba(74, 74, 74, 0.7);`
7. Remove `.card` border
8. Drop `.faq-card` box-shadow to `0 2px 4px 0 rgba(0,0,0,0.1)` (it looks more subtle and cleaner)

**Comment by arun1595** [comment]
@adachiu Thanks for the detailed feedback :+1: 

I'll make the suggested changes :)
