### ISSUE TITLE
React(NEW): Typo in Lesson block heading 'The React Ecocsystem' 

### ISSUE THREAD

**Issue by RushilJalal** [TheOdinProject/theodinproject#4034]
### Describe your suggestion

As you can see there is a typo in the aforementioned lesson block title.
![image](https://github.com/TheOdinProject/curriculum/assets/54212357/107352aa-64a5-491f-b19d-fc9a26f7ebba)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript/courses/react-new#the-react-ecocsystem

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

willyWonka

**Comment by 01zulfi** [comment]
Hello @RushilJalal, this issue is related to the website repository; I've transferred this issue over. 

Great catch on the typo. You should be able to find the lines you need to update in the following files: 

1. https://github.com/TheOdinProject/theodinproject/blob/5ae47989ad1d42ba0c045bac7534c8b3592b9e63/db/fixtures/paths/full_stack_rails/courses/react.rb#L90

2. https://github.com/TheOdinProject/theodinproject/blob/5ae47989ad1d42ba0c045bac7534c8b3592b9e63/db/fixtures/paths/full_stack_javascript/courses/react.rb#L90
