### ISSUE TITLE
UI: draft requirements

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/theodinproject#4525]
Just very broad strokes here, just starting here to get something to iterate over.

The page should mimic the rest of the site for the skeleton of the page (header, nav, footer)

For the simplest version(end to end) In the main section we would need:

- Title  
- Date picker (for date of the interview)
- Multiselect input ( for concepts covered)
- Submit button

Then, fleshed out, we'd want to add the following?

- Text explaining purpose of form
- Text explaining how to fill out form (ie tips)
- Small FAQ for how the data will be used/shared (accordion like the TOP FAQ)
- A success/failure notification to user upon submission (toast-style?)

**Comment by BryanF1nes** [comment]
Lets try to flesh this out some more based on Kevins comments.

## UI: Form Requirements
- [ ] User clicks "button" to be directed to survey form
- [ ] Check if feature flag is enabled
- [ ] Show the survey title and a brief paragraph explaining the purpose of the survey
- [ ] Display survey form
- [ ] Survey form will have multiple fields:
     - Interview Position Title
     - Date of Interview
     - Topics covered in interview
     - etc.
- [ ] Display a submit button that will submit the data and thank the user for taking our survey
- [ ] Redirect the user back to the dashboard/homepage

#### Note - Database information or Schema related information probably isn't needed in here since the main focus of this is the UI and what the user will be presented.

**Comment by JustWaveThings** [comment]
This all looks pretty good Bryan.

We did discuss that we aren't going to capture anything but the key information, to reduce the friction to getting the information we want from the user. I think we are only going to have two user inputs on the form-- date of interview datepicker, and topics covered multi-select.

Also, we do need to consider the non-happy path in the instance of form submission failure, or if the user attempts to navigate away from the page before submitting, the user should be warned that the information will not be saved/submitted.
