### ISSUE TITLE
<All paths Interface>: <Correct number of lessons in all paths interface>

### ISSUE THREAD

**Issue by BodiAli** [TheOdinProject/theodinproject#4542]
### Checks

- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Inside the all paths interface especially the JavaScript course the number of lessons do not match the actual number of lessons

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/paths/full-stack-javascript

### (Optional) Discord Name

bodiali.

**Comment by MaoShizhong** [comment]
Transferred to web app repo due to the subject matter.

@BodiAli Could you elaborate with some examples? The JavaScript course you linked shows 29 lessons and 12 projects, and within it, I count 29 lessons and 12 projects.

**Comment by BodiAli** [comment]
@MaoShizhong 
I'll drop in some screenshots, maybe the computer science part is what makes the number of lessons more than 29 lessons for me (I counted them)
![Screenshot from 2024-05-31 22-18-49](https://github.com/
![Screenshot from 2024-05-31 22-17-46](https://github.com/TheOdinProject/theodinproject/assets/150652018/e38b858f-02a8-4861-b644-8c43c4416d79)
TheOdinProject/theodinproject/assets/150652018/fb72d325-0ab0-4da1-9462-cd4eca2f1ca1)
![Screenshot from 2024-05-31 22-18-05](https://github.com/TheOdinProject/theodinproject/assets/150652018/51b3613d-b032-4a3e-96c0-658a4c434fd6)

**Comment by MaoShizhong** [comment]
@BodiAli I see. The dashboard interface combines lessons and projects into one count (29 lessons + 12 projects = 41, 23 React lessons + 3 React projects = 26 etc.)

I'll see what the team thinks about the use of the word "lessons" in the Dashboard overview, or potentially showing the split lesson/project counts there instead of the combined count.

**Comment by BodiAli** [comment]
@MaoShizhong Oh that makes a lot of sense thank you for clarifying

**Comment by MaoShizhong** [comment]
@BodiAli It would make sense for our dashboard view to display the split lesson/project counts for each course, exactly like how the current "All paths" version displays things.

I know you checked the "assignment" box, but want to check with you first since you may not have been expecting this to be a Ruby on Rails/ERB thing, given you posted this in the curriculum repo.

If you'd still like to be assigned to this, let me know, but if not then that's also completely fine.

**Comment by BodiAli** [comment]
@MaoShizhong I would love to be assigned to this, however just so you know I did not take the ruby course since you mentioned it

**Comment by MaoShizhong** [comment]
I'll assign you to this @BodiAli.
You can follow our [wiki instructions for setting up and locally deploying the TOP Rails app](https://github.com/TheOdinProject/theodinproject/wiki).
Once that's all up and running, you'll need to edit the ERB template for the course list in the dashboard interface so that the courses there use the split lesson/project counts that's currently used in the other interfaces.
