### ISSUE TITLE
All Course Assignments: A simple checklist next to each assignment to track progress. 

### ISSUE THREAD

**Issue by Fadirstave** [TheOdinProject/theodinproject#4589]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I would love to see a checklist next to each assignment in each chapter. It would be especially helpful for people like me (a stay-at-home dad). I often have to get up from my PC for dad **dooties** _pun intended_ and end up losing track. I've attached an example below!

Thanks!

![Example Checklist](https://github.com/TheOdinProject/curriculum/assets/7087861/9368e7b5-4678-4ea2-9d5e-346956dd21ab)

### Path

Other / NA

### Lesson Url

Any Assignment 

### (Optional) Discord Name

Fádir Stavé

**Comment by MaoShizhong** [comment]
Transferred to the web app repo since this would concern implementing a web app feature.

I'll defer to those who are more familiar with the web app codebase, but initial considerations which may even pose problems:
- Not all lessons/projects' assignment content follows the same structure as others, but will typically include an ordered list, which may also have nested lists (either ordered or unordered). There may also be non-list paragraphs between lists. I think I've also seen some lessons' assignment boxes contain only an unordered list at the top level. We would need to consider exactly how we determine which items are given checkboxes, especially when a list item might just be a brief summary and contain a nested list with lots of substeps (but these items may not necessarily be steps either but just hints). Then we'd of course need to determine exactly how to implement the checkboxes for those items.
- We'd need to consider how we approach checked status persistence.
- Related to the above, we'd also need to consider if such a feature would only be present if currently signed in on the website (i.e. no checkboxes if not signed in).

**Comment by CouchofTomato** [comment]
As already mentioned the main problem will be persistance. Assignments are just built up from the MD file so persisting them would be almost impossible. I like the idea but unfortuantely not something we can action with the current setup.
