### ISSUE TITLE
Feature Request: Better Git History Website

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/theodinproject#4632]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

Currently the **See lesson changlog** button will take the user to github file history tab. But I think this site will be more intuitive to use for learners:

(proposition)
https://github.githistory.xyz/TheOdinProject/curriculum/blob/main/javascript/computer_science/project_binary_search_trees.md

vs

(current)
https://github.com/TheOdinProject/curriculum/commits/main/javascript/computer_science/project_binary_search_trees.md

### Acceptance criteria

- [ ] Remove `github_commits_url` lesson helper
- [ ] Remove test for `github_commits_url` lesson helper
- [ ] Add `git_history_url` lesson helper
- [ ] Add test for `git_history_url` lesson helper
- [ ] Change the link for `See lesson changelog` to use `git_history_url` instead of `github_commits_url`

**Comment by AgustinRamiroDiaz** [comment]
@nikitarevenco I think you meant githistory.xyz/TheOdinProject/curriculum/blob/main/javascript/computer_science/project_binary_search_trees.md in the proposition

**Comment by nikitarevenco** [comment]
> @nikitarevenco I think you meant githistory.xyz/TheOdinProject/curriculum/blob/main/javascript/computer_science/project_binary_search_trees.md in the proposition (since the other link doesn't work for me)

Just tested and both links work for me
 Maybe there was an internal error or something?

**Comment by MaoShizhong** [comment]
Thanks for the suggestion. I think that site is pretty damn awesome! Though I feel that the current commit history page is actually more useful for the purpose. You can see the summaries of many commits all at once, and commit bodies are viewable via single toggle button. It's easier to find out what's changed over time rather than just what lines an individual commit has changed from the previous. With the (really nifty) git history site, you can't see a list of all past commits. I'd have to scroll through the commits to see what changed, and would have to open the commit itself in a new window to read any part of the title/body that was truncated. Whereas with the standard commit history, most meaningful commits will have descriptive enough names, so people can see what changes happened over time at a glance. Plus, it wouldn't hurt for people to get more familiar with the GitHub interface too!
