### ISSUE TITLE
Bug: Databases course doesn't show correct amount of lessons

### ISSUE THREAD

**Issue by incandesc3nce** [TheOdinProject/theodinproject#4672]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

Databases course has 3 lessons, but it's component shows that there are only 2 lessons (which, of course, is not true).

![image](https://github.com/user-attachments/assets/a5eeb63f-9485-4294-8960-f90e3bcf699a)

The issue persists only on amount of lessons, completion percentage works as intended. On screenshot below I completed 1 of 3 lessons in Databases course and it shows 33% completed (as intended).

![image](https://github.com/user-attachments/assets/a766db93-c931-44d1-9312-b6b846e93ca2)

I'm on a Fullstack JavaScript path, but the issue is the same in Ruby path.

### How to reproduce

1. Go to any of the path's cirriculum (FS JS / Ruby), dashboard also has this issue.
2. Scroll down to Databases course.
3. Databases course says that it has only 2 lessons.

### Expected behavior

1. Databases course should say that it has 3 lessons.

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

Windows

### Discord Name

coldmilka

### Additional Comments

If it's not something related to admin's part of the website, I would like to take on the issue and receive directions on where can I find the source code for this component.

**Comment by rlmoser99** [comment]
I do not believe this is a bug, but I'll leave this issue open to make sure @KevinMulhern agrees.

I think because of the database course has a small number, it seems like a bug. If you look at any other course, you will see that the number of lessons do not include the number of projects. I'll walk you through the code to try and help you understand.

Here are the lines of code that shows that the numbers from "2 Lessons, 1 Project"  that you are seeing. They are `course.lessons_count` and `course.projects_count`
https://github.com/TheOdinProject/theodinproject/blob/main/app/views/courses/_course.html.erb#L21-L26

`lessons_count` and `projects_count` are columns on the `courses` table
https://github.com/TheOdinProject/theodinproject/blob/main/db/schema.rb#L121-L122

In many ways we treat lessons and projects the same. When you look at the lessons listed in this file, you'll see that the project "SQL Zoo" has `is_project: true`, which is how we know to indicate that this lesson is a project.
https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/lessons/database_lessons.rb#L20

The percentage that you are seeing uses the number of a user's `lesson_completions` A `LessonCompletion` is the model name to represent when a user has completed a lesson or project. Here is the component that is getting the percentage.
https://github.com/TheOdinProject/theodinproject/blob/main/app/components/progress_circle/component.html.erb#L5

The percentage is defined in the `CourseProgress` file. You can see in this file that `completed_lessons` comes from the `user.lesson_completions`
https://github.com/TheOdinProject/theodinproject/blob/main/app/services/course_progress.rb

I understand the confusion of looking like you are 33% done, with 2 lessons. But if you add the number of lessons and projects together, it makes sense.

**Comment by incandesc3nce** [comment]
Thanks for clarification, that actually makes sense to me now. My apologies, I should've been more attentive. I will close the issue now, since nothing should be fixed.

**Comment by rlmoser99** [comment]
No problem. It's all good. I can totally understand the confusion. Thanks for taking the time to make an issue when you saw something not quite right with our website.
