### ISSUE TITLE
Redesign: Help us come up with a new slogan for the home page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#549]
Under the heading on the homepage we have the following text: 

"Stop wasting time...  Here's what you need to know."

This is a bit 💩 so we want to replace it with something better. If you have any ideas on what we should replace it with, please comment it below 😄.

Please also vote on the comment you like best by reacting to it with a 👍 

For a bit more context here is a screen shot of that section:

<img width="597" alt="screen shot 2017-05-24 at 18 44 57" src="https://cloud.githubusercontent.com/assets/7963776/26417433/1bd8929e-40b1-11e7-9b3b-8e023b30b074.png">

**Comment by tomasvn** [comment]
Together with the Mighty Odin you will conquer the world of Web Developement.
The Mighty Odin will guide down on the path of Web Developement.

**Comment by Demo318** [comment]
Looking at this issue, I consider it's a spot to place TOP's Value Proposition - though briefly.

To the uninitiated, a value proposition is a statement that summarizes: 1) How your service is a fit for what the client wants to do, 2) how it adds value to what they want to do (adds gains), 3) how it makes what they're doing easier (alleviates pains).

As a user, I would say that TOP 1) Provides a thorough, all-encompassing education (goals), 2) Connects me with other learners and experienced developers for community and support (gains) 3) Costs me no money and lets me learn at my own pace (an answer to the pains I feel with other services.

There might be many ways to summarize this into a tag line. Here's my attempt:

> A full suite of skills, community support, and no cost to you.

I think it'll take some revisions to find exactly what fits, but that model should help drive at something that will really catch people and encourage them to explore the website more thoroughly.

**Comment by KevinMulhern** [comment]
Thank you guys 😄

**Comment by davidchappy** [comment]
The Odin Community is currently answering a few questions to help understand our typical site visitor. This will not only help shape our tagline but also provide valuable information for any further content changes or additions:
1. What caused you to be interested in TOP?
2. If you came to web dev from another field, what was it that motivated you to make that change?
3. What about TOP helps you meet the desires mentioned in no. 2, better perhaps than another program or school out there?

I will collate the responses I get (in Gitter) and will post here along with observations.

**Comment by Alastair7** [comment]
Ideas :
Let us enhance the creativity inside you
We'll help you develop web applications with your very own Idea 
Let us build websites that's Smarter, Creative and Craft an experience for you
Let us be the origin off your innovative journey.

**Comment by mindovermiles262** [comment]
Are you still taking feedback in your google doc?

**Comment by davidchappy** [comment]
Absolutely. I was waiting to see if anyone had any other input before posting some of the suggested tagline. Please share!

**Comment by Demo318** [comment]
Does anyone have any interest to posting multiple tag lines?

If there were 10-15 good ones, either have them rotate based on a time frame or even use a random-number generator to pick one to show on page load?

Just a thought. I've seen it on other websites.

**Comment by Devimir** [comment]
Here's a couple I thought of.

Free Code Sorcery for the masses.

It's magic(it's code).

The code gods have spoken.

Move mountains with code.

Be a whiz too.

**Comment by davidchappy** [comment]
Here is the (publicly editable) Google Doc with the user research and tagline brainstorming. https://docs.google.com/document/d/1vuimQT7r75n8dgw2N_LD_TDmG50dlPd-8CNzPuPzAoY/edit#

For actual tag line suggestions/submissions (not just brainstorming), use the Suggested Taglines section on the first page. (for example: I have 8-10 lines of brainstorming right now, but only one suggested tagline). I've added what I'd consider the best from above suggestions.

Note the Observations section at the top (and feel free to comment/add/edit): those are the key things to remember when coming up with tag line ideas. And feel free to make use of the brainstorming section.

**Comment by okeharlyon** [comment]
Possible ideas

Your Career in Web Development is now
Its time to dive in to the world of Software Engineering

**Comment by davidchappy** [comment]
Below are some of the best Headline/Subheading taglines submitted - feel free to give some feedback here or in the Google doc linked above. 
Notice a couple objectives that we're trying for:
1. Focus on end goal (being a web developer) rather than just learning skills (unlike pretty much all the taglines on other learning websites). This is what most of our users care about.
2. Emphasis on completeness of curriculum.
3. Interesting, but not corny or weird. There's no compelling need to include the connection to Odin/Vikings/etc. Extending the metaphor into the brand language isn't helpful in this case I think (Apple computers never talks about apples in their brand language - they talk about their products).

--------- 

Headline: Become a Web Developer for Free
Subheading: Join the world's only open source full stack training program.
 
Headline: Want to Become a Web Developer? 
Subheading: This is your complete free path for learning all you need to know. 
 
Headline: Ready to Become a Web Developer?
Subheading: Our free curriculum gives you a complete learning path. Our open source community will help you complete it.
 
Headline: Your Career in Web Development is now
Subheading: Our full stack curriculum is free and supported by a passionate open source community. What are you waiting for?

**Comment by buoyantair** [comment]
Here's by bit

# Build global solutions to global problems
## Lets make a change
