### ISSUE TITLE
Redesign: Navbar bugs

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#634]
There are currently a couple of serious bugs with the mobile navbar.

* The hamburger placement has gone crazy (screen shot from an iphone 6s
* The menu items on landscape mode are all messed up

**Hamburger menu placement messed up**
![2017-07-16 19 46 26](https://user-images.githubusercontent.com/7963776/28388292-27307d6a-6cca-11e7-8cb6-809b67aef0d9.png)

**Landscape mode madness**
![2017-07-19 21 37 13](https://user-images.githubusercontent.com/7963776/28388410-90638b9c-6cca-11e7-926d-cdf785ab9f1b.png)

**Comment by mindovermiles262** [comment]
I'll snatch this up and try to figure it out

**Comment by KevinMulhern** [comment]
Thanks @mindovermiles262 🎉

**Comment by mindovermiles262** [comment]
Copy/Paste from July 16 Review Notes

**Navbar**
Remove outlines when clicked
- [x] Remove outline around avatar when clicked. < I think this is a bad idea
- [x] Remove outline on hamburger on mobile < ditto (http://a11yproject.com/posts/never-remove-css-outlines/ ….. https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/)
- [ ] what we CAN do is globally style the outline so that it’s a little more attractive… I’ll do the work if Ada can describe something that would go nicely.
- Doing the above would be an accessibility issue and is only really a problem when on mobile view on a desktop which is unlikely to happen often.

**Fix the user dropdown on mobile - wait until the bugs are fixed**

- [ ] Extract out nav links from avatar and display them below line on mobile view
- [ ] Remove the icons from the user links in mobile view

**Small fixes**

- [ ] 20px of padding between logo and text on both navbar and footer, check mobile view when done.

**Comment by mindovermiles262** [comment]
It appears the Firefox issue is stemming from the following line 22 in app/assets/stylesheets/components/navbar.scss

`background-image: url("data:image/svg+xml;charset=utf8,<svg%20viewBox='0%200%2032%2032'%20xmlns='https://www.w3.org/2000/svg'><path%20stroke='#6abfc3'%20stroke-width='2'%20stroke-linecap='round'%20stroke-miterlimit='10'%20d='M4%208h24M4%2016h24M4%2024h24'/></svg>");`

Disabling this style renders the un-stylized hamburger menu, although still out of place

**Comment by KevinMulhern** [comment]
@mindovermiles262 after playing around with it on safari, including the vendor prefixes for flexbox in the `navbar` class put the hamburger back in position.

**Comment by mindovermiles262** [comment]
Reference to Previous Navbar PRs
#505 >> #619 
#558

**Comment by davidchappy** [comment]
@mindovermiles262 From our chat to today, while you're working on this, in navbar.js:
1. Please remove the console logs
2. Please refactor function to be called only if user agent is an iOS device. 
Feel free to bump back to me if you run out of time!

**Comment by KevinMulhern** [comment]
@mindovermiles262 I'm going to close this and create another issue for your current work on restructuring the nav.
