### ISSUE TITLE
time feature - Estimated time for every course 

### ISSUE THREAD

**Issue by kawaqui** [TheOdinProject/theodinproject#755]
It will be good to have an estimated time required to complete every step or part.

**Comment by codyloyd** [comment]
we've discussed this feature quite a lot actually... our decision is that it is likely do to more harm than good.   Because of the very flexible nature of our program the time to complete a lesson can be wildly different for each person.  Having estimated times can cause people to feel bad about their progress, or rush through a lesson to meet a time goal and miss something important.
