### ISSUE TITLE
On Screen Chat: Active Focus colors

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#773]
When clicked, (:active && :hover), the close button of the chat turns a purple color (see photo).  Removing `outline:focus` resolves this issue, but maybe interferes with accessability (@codyloyd ?)

<img width="581" alt="screen shot 2017-10-14 at 10 32 54 am" src="https://user-images.githubusercontent.com/14863257/31577947-27831962-b0cc-11e7-8def-3590c4db568d.png">

**Comment by mindovermiles262** [comment]
> If you remove the outline you are making your site inaccessible for these people.
http://www.outlinenone.com/

Possible Alternatives: http://a11yproject.com/posts/never-remove-css-outlines/

**Comment by KevinMulhern** [comment]
I'll leave this to our resident accessibility expert @codyloyd  to decide on which solution we should go with 😄

**Comment by codyloyd** [comment]
this happens because they're using a filter to turn the button red when it's focused.. which as a side effect turns the focus ring that dumb pink color.

solution: override this rule in our CSS somewhere
```
.gitter-chat-embed-action-bar-item:active {
    box-sizing: border-box;
    -webkit-filter: hue-rotate(80deg) saturate(150);
    filter: hue-rotate(80deg) saturate(150);
}
```

just say `filter: none` and `-webkit-filter: none;`

If I have time this afternoon I can solve the issue.. but someone else might be able to get to it sooner.

**Comment by mindovermiles262** [comment]
I will knock this out momentarily
