### ISSUE TITLE
List alignment in lesson content

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#781]
Lists should be flush left aligned with the rest of the content in a lesson, but currently they are not.

Check out this lesson for an example https://staging-odin-project.herokuapp.com/courses/getting-hired-as-a-web-developer/lessons/it-starts-with-you

**Comment by leosoaivan** [comment]
Is this in regards to the numbered lists?

**Comment by KevinMulhern** [comment]
@leosoaivan yeah exactly, when it gets to double digits the alignment gets all screwed up 😄

**Comment by leosoaivan** [comment]
It appears to be a simple fix, but the indents of the list items follows the alignment of the numbering.

![image](https://user-images.githubusercontent.com/13614862/32050080-94052ecc-ba1d-11e7-8609-7bb4590cd545.png)

It might be possible to re-indent the list items if they are wrapped in a padded `<span>` element, but I'm not sure how that would work since the content is piped in from the curriculum github. One alternative is to have the `ol` elements displayed as a table, but that messes up all the styling and numbering.

![image](https://user-images.githubusercontent.com/13614862/32050590-5fe814ae-ba1f-11e7-8b5d-da7de8f431f0.png)

Thoughts?
