### ISSUE TITLE
Broken link in https://www.theodinproject.com/lessons/oop

### ISSUE THREAD

**Issue by heyalvaro** [TheOdinProject/theodinproject#882]
Inside https://www.theodinproject.com/lessons/oop there's a paragraph that says 

> Student Solutions
> Submit a link below to this file on the ruby course github repo with your files in it by using a pull request. > See the section on Contributing for how.

The link for _this file_ is [https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/intermediate_ruby/oop_project.md](url) and it's broken. I'll fix it as soon as I can

**Comment by heyalvaro** [comment]
Basically the link has to be changed from:
https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/intermediate_ruby/oop_project.md
to:
https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/intermediate_ruby/project_oop.md

**Comment by heyalvaro** [comment]
@KevinMulhern I've forked theOdinProject website repo and followed the steps of the wiki. When I run rspec I pass all the unit tests but with cucumber that's not the case. What am I missing to be able to fix the link? Thanks! (I'm attaching the output of the cucumber command)
[output.txt](https://github.com/TheOdinProject/theodinproject/files/1817310/output.txt)

**Comment by KevinMulhern** [comment]
Hi @heyalvaro, the cucumber tests have been broken since the redesign. We've been planning on replacing them with RSpec feature tests. Thats why we haven't fixed them.

For the broken link, you'll have to edit it on the ruby_course repo instead of this repo. This is the file where the lesson content for that project lives https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/intermediate_ruby/project_oop.md

We pull in the content for lessons on the site from our course repos.
