### ISSUE TITLE
Remove Eager Loading From UserController#show Action

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#891]
As @chancancode discovered and explained in this PR https://github.com/TheOdinProject/theodinproject/pull/890 using includes to eager load lessons is a bad idea due to the size of the content column on each lesson. 

As a follow up to what Chan has done we should also remove eager loading lessons from the UsersController#show action as well.

**Comment by chancancode** [comment]
@KevinMulhern my apologies, I just realized I am somewhat wrong about this: the `CoursesController#show` does in fact need to use the lesson title for the list, so the eager loading is probably justified. Normally you can use [`select`](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-select) to prevent it from including the `content` (since it's not needed) but I'm not sure that it works for eager load.

There is still probably something to do here, but it requires being a bit more creative than I originally thought!

The Dashboard, however, probably could use very similar treatment to #890, since it's showing almost exactly the same thing.

**Comment by KevinMulhern** [comment]
Ah of course, that makes sense @chancancode. I'll update this issue to address the dashboard instead.

**Comment by OmarMoataz** [comment]
Is someone working on this feature or can I take it?

**Comment by KevinMulhern** [comment]
I think this _might_ have been taken care of in a unrelated refactor @OmarMoataz, we're no longer eager loading lessons in the users controller by the looks of it https://github.com/TheOdinProject/theodinproject/blob/main/app/controllers/users_controller.rb

Looks like this one can be closed, thanks for bringing it to our attention 😄

**Comment by OmarMoataz** [comment]
No worries.
