### ISSUE TITLE
Design: Certificate for completion of TOP courses

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#899]
I designed a certificate for graduates of the Full Stack course. @KevinMulhern please review the content of the certificate to see if we need to add more information.

This is letter size so students could actually print it out if they want. We can provide the print-ready file for them to download.

![odin certificate sample](https://user-images.githubusercontent.com/13413986/40074444-38a3b00c-58ac-11e8-93b6-0c8d7b7f8e77.jpg)

Free handwriting font used:

[HunterRiver-Regular.otf.zip](https://github.com/TheOdinProject/theodinproject/files/2005625/HunterRiver-Regular.otf.zip)

**Comment by KevinMulhern** [comment]
It looks perfect @adachiu 😍 

The only thing that needs changed in the final version is my signature replaced with something else 😂 Maybe something like "The Odin Project Team".

**Comment by KevinMulhern** [comment]
@TheOdinProject/odinmods what do you guys think about the design?

We still need to talk a lot more to hash out implementation details and requirements for getting a certificate.

**Comment by codyloyd** [comment]
i think it looks great

**Comment by adachiu** [comment]
@KevinMulhern The stamp side says "issued by TOP" so it would be redundant if we had "The Odin Project Team" on the left side (or maybe not). I find it to be more authentic if it was a moderator name who verifies the student. The downside to having an actual name for verification is that it always needs to be changed.

Or if we want it to be more fun, we could just use the name "Odin" as the verifier.

**Comment by leosoaivan** [comment]
:100:

**Comment by KevinMulhern** [comment]
ahh I see @adachiu, good point about authenticity. In that case I reckon the signature will depend on how we implement this.

If it's one certificate for the entire curriculum I think it should be a Mod's name chosen at random.

If its a certificate per course then the name of owner of that course should be on it imo.

The verification stuff adds another dynamic. Theres a few differing opinions on how we should do it so that needs to discussed and decided upon as a team. If the verification needs to be a manual process then the verifier should get the honour of having their signature on it imo.

**Comment by miarhost** [comment]
Looks good

вт, 15 мая 2018 г., 21:20 Kevin Mulhern <notifications@github.com>:

**Comment by adachiu** [comment]
@KevinMulhern How many owners are there for a single course? would these owners change? Should certificates only be handed out to completion of the Full Stack instead of individual courses?

**Comment by adachiu** [comment]
@KevinMulhern One certificate for the curriculum would be perceived as more valuable than having separate ones for each course. Also, since the home page says` "Our full stack curriculum is free and supported by a passionate open source community."` I think that we just want to focus on awarding students with the completion of "full stack curriculum."

**Comment by KevinMulhern** [comment]
@adachiu Great points, we should maybe start a conversation about the verification process in the forum.

**Comment by adachiu** [comment]
@KevinMulhern Maybe we could consider recreating this certificate with html and css and just change the verification name and student name each time.

**Comment by KevinMulhern** [comment]
@adachiu definitley lets do that 😄 it would be nice if it was accessible from the students dashboard once they've got it.

**Comment by KevinMulhern** [comment]
Thanks for pitching into this discussion, @I3uckwheat. I completely agree with all you've said. @RobPando had similar thoughts about this. I was planning on putting this idea forward after we finish the current batch of sprints (Codys JS one, and the rspec one).

If you're free then we'd love to have your help with it.

**Comment by AREEBAISHTIAQ** [comment]
The certificate looks great

**Comment by I3uckwheat** [comment]
@KevinMulhern I'd love to help with this.

**Comment by adachiu** [comment]
Included verification # in this version. Also reduced the student name sizing so we could accommodate names that are longer.

![odin certificate sample v2](https://user-images.githubusercontent.com/13413986/41450033-857bf03a-7097-11e8-8d6a-9cfa2ff1ced9.jpg)

**Comment by I3uckwheat** [comment]
I feel this should be a PDF that is generated and tied to the users Odin account. That would make verification numbers easy to track and link to a user.

**Comment by meansh** [comment]
Yeah ! That's perfect.

**Comment by DoviMaj** [comment]
Just my two cents. When issuing a certification it needs to mean something for real. that the person has at least made all the projects because the lessons I can just click complete on each one.

Now the problem with the projects is that no one is really checking to see if they pass all of the requirements. Correct me if I'm wrong. When browsing the solutions I often see solutions that don't even work minimally. How could this be addressed?

**Comment by I3uckwheat** [comment]
@DoviMaj This has been a hot-topic issue of debate for the last year in the core team. 

It's likely that the certificate won't become reality here at TOP due to the exact reasons you've outlined. We can't certify somebody knows stuff, only completion. And completion certificates are pretty worthless. Most of us believe that things like this are worthless to employers unless it is a full degree. This is something that is VERY time consuming to solve, and likely will not become a reality.

**Comment by ChargrilledChook** [comment]
@KevinMulhern I'm assuming this is no longer planned? Can we close it out? We can convert it to a discussion if we'd like to keep the conversation around it for posterity

**Comment by KevinMulhern** [comment]
@ChargrilledChook Yeah lets close it, haven't been hearing much about learners requesting certs lately aha.
