### ISSUE TITLE
Feature request: Leaderboard for Ruby exercises

### ISSUE THREAD

**Issue by dvik1950** [TheOdinProject/theodinproject#905]
My idea was to implement a leaderboard on the website or in the ruby course that would list all TOP members on Exercism and the amount of exercises completed ( maybe a point system too, where completed exercises who use methods that are faster (less iterations) would be awarded more points, but those are just details). 

This could be a nice motivation to do ruby exercises on a daily/weekly basis and see how you compare to other students.

I tried looking into the Exercism API documentation but with no luck. I would like to help in the implementation process (Of course, if you agree with this idea) but I would need some guidance on how to do this.

**Comment by CouchofTomato** [comment]
Hi @dvik1950 

Thanks for the idea. I really like it and could be part of our drive for gamification features to try to interact more with the wider community.

I will make a note to explore the exercism api and see and when I've got an idea of feasibility will reach out to you if you are interested in helping.

**Comment by OmarMoataz** [comment]
I'd like to tag along on this if and where you start working on it.

**Comment by javierojeda94** [comment]
I would like to help too!

**Comment by dvik1950** [comment]
Could exercism be replaced with CodeWars? Their [API endpoint](https://dev.codewars.com/#authentication) seems pretty straight forward. Is a feature like this still an option and if it is, would anyone be interested in exploring this option with me and eventually implementing it ?

**Comment by I3uckwheat** [comment]
I don't think we want this even though it would, indeed, be cool to see the amount of points some one has. Not only will it distract users from TOP, I don't think we want to have people comparing themselves with others in this way. It's one thing to see an alternative solution to a problem, and another thing to see someone's points on a leader-board. 

I understand we have this in the chat, but it's points given from others instead of embracing the grind. 

On top of that, there are many implementation issues with this, and that would distract from more important changes that need to be made.
