### ISSUE TITLE
Make "Student Solutions" Section Expandable 

### ISSUE THREAD

**Issue by marko-avlijas** [TheOdinProject/theodinproject#951]
Student Solutions section is taking up lots of space. It's making it hard to see how far I have progressed and even if there are remaining projects left or not.

I suggest you hide it behind bootstrap collapse element: https://getbootstrap.com/docs/4.0/components/collapse/
It should be hidden by default.

**Comment by KevinMulhern** [comment]
Hey @marko-avlijas, We have an ongoing project to solve this problem, hiding them behind a collapsable element would be a good short term solution. But I'd worry about students missing the solutions because they are hidden.

**Comment by marko-avlijas** [comment]
I don't think that's a concern. I think just text saying `Show Student Solutions` which changes into `Hide Student Solution` is enough. If not,  perhaps a paragraph of text could explain that you can view student solutions here and why you should do it or whatever.

What kind of solution did you have in mind?

**Comment by 02zchen** [comment]
I am a student learning from TOP and I agree with marko on this issue. I am still a novice at bootstrap, but here are my two cents: If you really are worried about the students missing the information, I feel like you could have a few good examples listed straight out and then have the rest in a collapsible element.

**Comment by CouchofTomato** [comment]
Thanks for the input. The ongoing project isn't just around how to hide student solutions but where they should be stored. Currently they are just entered as an input on the markdown file on github but we are considering storing them in the db so that for any user you can see their submitted solutions in one place. It would allow us to let people vote for the solutions they like and sort the student submissions in various ways.

It would also allow us to look into developing a certificate for completion of the course.

Whether there is the appetite in the meantime to just have something you can toggle I'm not sure.

**Comment by CouchofTomato** [comment]
You can read the install guide to get set up.

[Linux](https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide)
[Mac](https://github.com/TheOdinProject/theodinproject/wiki/OSX-Installation-Guide)

**Comment by AREEBAISHTIAQ** [comment]
Hi guys, I created [this issue](https://github.com/TheOdinProject/curriculum/issues/8896) and i thought that adding the bootstrap collapse element the solution for this.  
but @105ron said **I think the solution to this will be moving the student solutions to a resource in the app and having a react front end** and maybe it's much better than adding bootstrap collapse.
so, are we going to do what @105ron  said?

**Comment by CouchofTomato** [comment]
Hi @AREEBAISHTIAQ 

There is work in progress to make the student solutions submittable through the site rather than a github request. Once that is done we will have a better idea about displaying them.

**Comment by OmarMoataz** [comment]
I would like to further expand upon this suggestion. Would it be possible to add integration to the forum next to every project submission so it makes it easier for people to discuss the code in a specific submission because I tend to look at other people's code and might have feedback that I could give if it were easier to do so. I'm not saying this should be listed as forum posts. Maybe we could make it as a separate area but still using discourse. Let me know what you think!

**Comment by morrowdavidson** [comment]
A easy quick solution in the mean time might be to hide the solutions behind a `<details>` element. I made a [pull request]https://github.com/TheOdinProject/curriculum/pull/9673/commits where I did this for Lessons with 2 assignments. I could do it everywhere if there is interest.

**Comment by morrowdavidson** [comment]
Can be closed with a curriculum merge https://github.com/TheOdinProject/curriculum/pull/9999

**Comment by KevinMulhern** [comment]
Thanks @morrowdavidson
